host.system: linux

instances:
  - otel.poll.interval: 25
    otel.callback.interval: 30
    #otel.backend.url: http://localhost:4317
    otel.backend.url: http://localhost:4318
    otel.transport: http+prometheus
    prometheus.port: 16543
    otel.service.name: MyLinux
