
instances:
  - queueManager: VENUS
    isLocal: true
    #user: liurui
    #password: xxxxxxxx
    #host: 192.168.1.1
    #port: 1414
    #channel: SYSTEM.ADMIN.SVRCONN
    queuesMonitored: Q*
    #customEventQueues:
    #keystore:
    #keystorePassword:
    #cipherSuite: TLS_RSA_WITH_AES_256_CBC_SHA256

    ## Data collector properties:
    otel.poll.interval: 25
    otel.callback.interval: 30
    #otel.backend.url: http://localhost:4318
    otel.transport: prometheus
    prometheus.port: 16543

  - queueManager: SATURN
    isLocal: true
    #user: liurui
    #password: xxxxxxxx
    #host: 192.168.1.1
    #port: 1414
    #channel: SYSTEM.ADMIN.SVRCONN
    queuesMonitored: Q*
    #customEventQueues:
    #keystore:
    #keystorePassword:
    #cipherSuite: TLS_RSA_WITH_AES_256_CBC_SHA256

    ## Data collector properties:
    otel.poll.interval: 25
    otel.callback.interval: 30
    #otel.backend.url: http://localhost:4318
    otel.transport: prometheus
    prometheus.port: 16543
